### ISSUE TITLE
.

### ISSUE THREAD

**Issue by epikao** [chandong83/stm32_i2c_to_usb_hid_multitouch#2]

**Comment by chandong83** [comment]
hello, Did you solve the problem?
I put the following code in "touch.c" and tested it and confirmed that it worked.

void touchTest()
{
	static uint8_t step=0;

	if (step == 0)
	{
		tpd_down(100, 100, 0);
		tpd_down(200, 200, 1);
		//send data
		input_sync();
		step = 1;
	}
	else if (step == 1)
	{
		tpd_up(100, 100, 0);
		tpd_up(200, 200, 0);
		//send data
		input_sync();
		step = 2;
	}
	else if (step == 2)
	{
		tpd_down(1000, 1000, 0);
		tpd_down(1100, 1100, 1);
		//send data
		input_sync();
		step = 3;
	}
	else if (step == 3)
	{
		tpd_up(1000, 1000, 0);
		tpd_up(1100, 1100, 0);
		//send data
		input_sync();
		step = 0;
	}
	HAL_Delay(1000);
}

You can check the video in the link below.
https://youtu.be/_ofgHura1hs

thank you
